services:
  - type: web
    name: BWSSCR
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"